# Generated by Django 5.1.3 on 2024-12-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(max_length=1000, unique=True)),
                ('subdomain', models.CharField(max_length=50, unique=True)),
                ('framework', models.CharField(choices=[('reactjs', 'reactjs'), ('angular', 'angular')], default='reactjs', max_length=100)),
                ('install_command', models.CharField(blank=True, max_length=100, null=True)),
                ('build_command', models.CharField(blank=True, max_length=100, null=True)),
                ('serve_command', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
